---
apiVersion: v1
kind: Ingress
metadata:
  labels:
    app: pwpush
    component: ingress-controller
    type: nginx
  name: pwpush-ingress
  namespace: pwpush
spec:
  rules:
  - host: pwpush.local
    http:
      paths:
      - backend:
          serviceName: pwpush-http
          servicePort: 5100
        path: /
        pathType: ImplementationSpecific